doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                type: annotation
                is_bundle: false
                dir: '%kernel.project_dir%/src/Marketplace/User/Infrastructure/DoctrineMapping'
                prefix: 'App\Marketplace\User\Domain\Entity'
                alias: User
            Shop:
                type: annotation
                is_bundle: false
                dir: '%kernel.project_dir%/src/Marketplace/User/Infrastructure/DoctrineMapping'
                prefix: 'App\Marketplace\Shop\Domain\Entity'
                alias: Shop
