# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        build: ./docker/images/nginx
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./:/usr/share/nginx/mitra-shop.loc
            - ./docker/logs/nginx:/var/log/nginx
            - ./docker/hosts:/etc/nginx/conf.d
        links:
            - php
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./docker/images/php
        # монтируем директорию с проектами
        expose:
          - "2375"
        volumes:
            - ./:/usr/share/nginx/mitra-shop.loc
    mysql:
        build: ./docker/images/mysql
        ports:
            - "3306:3306"
        volumes:
            - /docker-data/mysql:/var/lib/mysql
            - /docker-data/mysql-files:/var/lib/mysql-files
            - /docker-data/etc/mysql:/etc/mysql
            - ./docker/logs/mysql:/var/log/mysql
            - ./docker/data:/docker-entrypoint-initdb.d
        # задаем пароль для root пользователя
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: sait
