controllersUser:
    resource: ../../src/Marketplace/User/Application/http/Controller/
    type: annotation

controllersShop:
    resource: ../../src/Marketplace/Shop/Application/http/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
